### ISSUE TITLE
Frozen login 

### ISSUE THREAD

**Issue by J4zzy235** [OpenFusionProject/OpenFusion#208]
Yo, just joined. Only here to play the game. But unfortunately i hit a snag when attempting to login. 
first try went smoothly till i created my character name, i clicked continue and it froze for a good 10 minutes before i Xed out the window. Now i go to login and i click login and it freezes there instead. not quite sure what to do at this point.

**Comment by CakeLancelot** [comment]
The public servers may have been down due to a crash when you tried to log in, causing the GUI to freeze as you described. At the time of writing, both public servers are online - but if you encounter the issue later I would recommend waiting a little bit, then try to log in again.

Additionally, the issues page is more tailored towards developers reporting bugs with the server software. If you need assistance setting up the game or want to check the server status, I would recommend joining the [community Discord](https://discord.gg/DYavckB).

Closing this as the problem should be resolved
