### ISSUE TITLE
Enemies dealing too much damage/nanos not healing a lot in Academy

### ISSUE THREAD

**Issue by jjpinhoj** [OpenFusionProject/OpenFusion#220]
In the latest beta of academy the enemies seem to do way more damage then I remember (died to spiders in the tutorial multiple times when I can’t even remember dying unless I was just was too underleveled for an area on Original servers) and my nanos barely heal a 5th of my health and are almost pointless. Is this an issue in the game or were the damage/heal values changed for this build?

**Comment by CakeLancelot** [comment]
The health restored from a nano ability depends on its target type - in this case Alien X's area heal does much less than say, Eddy's self heal. So I'd say this is normal behavior.

Enemy damage is also read directly from a dump of the game's data, so damage amounts should be accurate. It's possible to get easily swarmed by the spiders in that specific area, so that may be why it seems like it's doing so much damage.

Closing this for now
