### ISSUE TITLE
FusionaFall port

### ISSUE THREAD

**Issue by Lorafen223** [OpenFusionProject/OpenFusion#232]
Hi. I just wanted to ask if it would be possible for you to make/if you would make an android port of this game.

**Comment by gsemaj** [comment]
Hey there,

There seems to be a pretty common misconception going around, so just to clarify: we don't develop the client for FusionFall itself. We just write server and launcher software to keep the original game working. As such, we don't have any intentions of making any ports for the game since clientside development isn't a goal of the project.

Hope that clears things up.
