### ISSUE TITLE
Computress Mission

### ISSUE THREAD

**Issue by carpengui** [OpenFusionProject/OpenFusion#239]
Level 22 World Mission:  Computress Support (Part 2 of 2)
The main task is to visit and protect Mandroid M-80 against a cyberattack from Fuse.
However, the mission actually directs you to Mandroid M-114.

It's a coin-flip call whether M-114 or M-80 is the correct bot to visit... M-114 is in the fountain area between Dexter's lab and Mandark's.  M-80 is standing beside Mandark.

**Comment by gsemaj** [comment]
@CakeLancelot @dongresource have you guys taken a look at this at all?

**Comment by CakeLancelot** [comment]
> have you guys taken a look at this at all?

This is an issue with the game's tabledata rather than the actual server implementation. [[1](https://www.youtube.com/watch?v=oLIdVv2Fv9I)] [[2](https://www.youtube.com/watch?v=xVCJFd1VEHw)]

This could in theory be fixed with a client patch, however it is out of scope of the project for now. Closing.
