### ISSUE TITLE
Network Error after Tutorial 

### ISSUE THREAD

**Issue by GhostKing2099** [OpenFusionProject/OpenFusion#241]
Can't get past the tutorial without the error even if I skip the tutorial.

**Comment by CakeLancelot** [comment]
'Network Close' errors can be due to AV program interference, for example Norton, AVG, and Avast are all known to cause this. It can also be due to an unstable connection (ex. weak Wi-Fi signal). 

Please check that both of these are not an issue and try again. If you need more help we have a tech-support channel on our Discord, or you can open a new topic under the Discussions tab here on Github.

Closing as this is not a codebase related issue.
