### ISSUE TITLE
Possible missing non-directory attribute in the database file

### ISSUE THREAD

**Issue by Juansecu** [OpenFusionProject/OpenFusion#258]
Hi. I'm trying to use a Docker container with the database file, and when I create the Docker container using the CLI, there are no issues, but when I try to create the Docker container using Docker Compose, the database file is considered as a directory.

Do you know what could be the cause?

By the way, I attach a screenshot of the Docker Compose I'm using to create the container.

<img width="1280" alt="image" src="https://github.com/OpenFusionProject/OpenFusion/assets/43616657/0ffdc1d7-c730-4b53-8fcf-d02b44fca4e9">

<img width="1280" alt="image" src="https://github.com/OpenFusionProject/OpenFusion/assets/43616657/938e7f16-8355-484a-9a10-7002bc33ba2b">

**Comment by gsemaj** [comment]
Sorry, just now getting the chance to look at this.
Just an FYI, Docker support for OF is minimal. The biggest caveat is that we're currently leaving it up to the user to configure the database (as you've discovered).
I'm pretty sure your problem is that your volume is configured incorrectly. You're trying to use the database **file** as a **volume**. Volumes in docker are file systems and can be thought of as a folder where you can store arbitrary files.
I think what you want is a folder **containing** your database.db, and then you can point your volume to that folder. You would probably also have to change the path to the database file in your config.ini to account for that. Hope that helps!

Closing as this is a docker configuration issue and not anything wrong with the Docker image.

**Comment by Juansecu** [comment]
@gsemaj Thanks for your answer.

I actually resolved that issue (not sure how, to be honest), but yeah, it is being recognized as a file now.
