### ISSUE TITLE
Nano icons will occasionally not appear on the Academy build

### ISSUE THREAD

**Issue by xmrshoot** [OpenFusionProject/OpenFusion#262]
![image](https://github.com/OpenFusionProject/OpenFusion/assets/129559513/5f0a0c18-9e8a-4dda-ba7c-8c681535ca24)

**Comment by xmrshoot** [comment]
and its not only problem for me, i asked other players and same problem

**Comment by CakeLancelot** [comment]
It might be worth trying to send a `sP_FE2CL_REP_RELOAD_CHAR` packet after the first `sP_CL2FE_REQ_PC_LOADING_COMPLETE`. I wouldn't be surprised if this is what the original game did to work around potential race conditions surrounding resizing the nano array.

**Comment by yungcomputerchair** [comment]
The `aNanoBank` and `aNanoSlots` fields in `sP_FE2CL_REP_RELOAD_CHAR` appear to be ignored by the client. I don't actually think we need more than our existing `sendNanoBookSubset()` function; moving the call to after (or during) handling of `sP_CL2FE_REQ_PC_LOADING_COMPLETE` as you suggested might be the right move.

I don't think we can be sure what the right solution is until we fully understand why this race condition is happening in the first place; I'll dig into the client code and see if I can root cause the issue.

**Comment by yungcomputerchair** [comment]
Actually, this bug seems to have 100% repro if the client manages to processes `P_FE2CL_REP_NANO_BOOK_SUBSET` _after_ loading in, so the solution seems to be reliably getting that packet over before sending `P_FE2CL_REP_PC_ENTER_SUCC`.. investigating
