### ISSUE TITLE
Trouble downloading assets

### ISSUE THREAD

**Issue by Walababi** [OpenFusionProject/OpenFusion#269]
When I click on the connect button to join the sever I get a loading/downloading screen and the progress bar never moves and after a while I get a message saying "Could not download assets" and "Could not connect to host".

**Comment by CakeLancelot** [comment]
Please report any issues with the public server on the Discord rather than the issues page, as this is only meant to report issues with the software itself.

To resolve your issue, I would ensure the following:
- Your internet connection is working and stable
- You are using the latest version of the client (currently 1.5.1 - can be found on releases page)
- Your network is not intercepting plaintext HTTP traffic (e.g. Hotel or School WiFi)
- Your PC has an IPv4 address, not just a IPv6 address

If you're not able to resolve it after following those steps, post a message in the Discord's #tech-support channel with the details and I'll get to it when I can.

Thanks,
