### ISSUE TITLE
question!

### ISSUE THREAD

**Issue by Corior48** [OpenFusionProject/OpenFusion#296]
is there any plans for a macos build of openfusion? just curious to know is all

**Comment by CakeLancelot** [comment]
The server, which is the software that tracks and syncs all players across the network, runs on MacOS natively. 
However I'm guessing this question is more about the client, which is the part you interact with to actually play the game. 

At the moment the client (or to be more specific, the Unity Web Player plugin) is only for Windows. Technically, there *was* a version of the plugin released for MacOS back when FusionFall first came out, however due to various updates (namely macOS 10.15 killing off 32 bit apps), it is no longer feasible to run it on modern machines.

I would advise using Parallels or VMWare Fusion to emulate a copy of Windows, then simply install the game on that.
