### ISSUE TITLE
Attacking while on vehicle bug

### ISSUE THREAD

**Issue by Frizy0** [OpenFusionProject/OpenFusion#49]
Attacking while on vehicle makes the getting off animation played several times as well as the audio.
Source: https://www.youtube.com/watch?v=Ywq11s9v8sE

**Comment by CakeLancelot** [comment]
We should probably also send a fail packet when the player doesn't have a vehicle - currently it plays the sound as if you were getting on the vehicle but nothing happens.

**Comment by CakeLancelot** [comment]
Seems to be fixed with #51?

**Comment by Frizy0** [comment]
> Seems to be fixed with #51?

Still present for me, just tried.

**Comment by CakeLancelot** [comment]
That's weird, it works fine on a local server. I'll look into this further later on

**Comment by CakeLancelot** [comment]
The cause of this is the client sending multiple ``P_CL2FE_REQ_PC_VEHICLE_OFF``, but only when attacking for whatever reason. It's less noticeable on a local server, since there's little to no latency. The fix is probably to only send a ``VEHICLE_OFF_SUCC`` after the last received ``VEHICLE_OFF`` packet, or to implement some sort of cooldown.

**Comment by CakeLancelot** [comment]
Should be fixed when #143 is merged.
