### ISSUE TITLE
I LOST MY ACCOUNT

### ISSUE THREAD

**Issue by Ssbhawk** [OpenFusionProject/OpenFusion#89]
I don't know why, but for some reason, when I logged in, it played the tutorial, despite the fact I had long completed it! I tried it 3 times, same username and password as always, and it acted like it was a new account! I even played earlier today, and it remembered me, but all of a sudden, it acts like I don't exist! What happened?

**Comment by CakeLancelot** [comment]
Yes this is intentional, it was announced on our Discord that characters (but not accounts) would be reset with the latest update. On the bright side, we now store more things on logout: inventory, equipped weapons, last location, etc.

As OpenFusion is in development and far from finished, stuff like this is due to be expected.

**Comment by Ssbhawk** [comment]
Oh. ok, thanks.

**Comment by Raymonf** [comment]
I just need to explain here that OpenFusion isn't a server. It is an emulator for the FusionFall client that happens to have an "official" testing server. If the game becomes playable, I reckon we should probably wipe the database every night on the public server. /shrug
